name: Kickbox Integration Plugin Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-kickbox-integration:
    name: Test KickBox integration Plugin
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: wordpress_test
          MYSQL_USER: wordpress
          MYSQL_PASSWORD: wordpress
        ports:
          - 3306:3306
        options:
          --health-cmd="mysqladmin ping --ssl-mode=DISABLED"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    container:
      image: php:8.1-cli

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Composer
        run: |
          # Download and install Composer
          curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          composer --version

      - name: Install dependencies
        run: |
          # Update package list
          apt-get update
          
          # Install additional PHP extensions and system dependencies
          apt-get install -y libzip-dev zip unzip git subversion default-mysql-client
          docker-php-ext-install zip pdo pdo_mysql mysqli
          
          # Install WP-CLI
          curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
          chmod +x wp-cli.phar
          mv wp-cli.phar /usr/local/bin/wp
          
          # Verify installations
          php --version
          wp --version --allow-root

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Install WordPress test suite with WooCommerce
        run: |
          # Install WordPress test suite with WooCommerce (this will create /tmp/wordpress)
          bash bin/install-wp-tests.sh wordpress_test wordpress wordpress localhost latest true 10.2

      - name: Copy plugin to WordPress plugins directory
        run: |
          # Create plugin directory in the WordPress installation
          mkdir -p /tmp/wordpress/wp-content/plugins/kickbox-integration
          
          # Copy plugin files (excluding .git, node_modules, etc.)
          rsync -av . /tmp/wordpress/wp-content/plugins/kickbox-integration/
          
          # Set proper permissions
          chmod -R 755 /tmp/wordpress/wp-content/plugins/kickbox-integration

      - name: Debug environment
        run: |
          # Debug: Check if WooCommerce is installed
          echo "Checking WooCommerce installation..."
          ls -la /tmp/wordpress/wp-content/plugins/ || echo "WordPress plugins directory not found"
          ls -la /tmp/wordpress/wp-content/plugins/woocommerce/ || echo "WooCommerce not found"
          
          # Debug: Check plugin files
          echo "Checking plugin files..."
          ls -la /tmp/wordpress/wp-content/plugins/kickbox-integration/includes/ || echo "Plugin includes directory not found"
          
          # Debug: Check WordPress installation
          echo "WordPress installation structure:"
          ls -la /tmp/wordpress/

      - name: Run PHPUnit tests
        run: |
          # Set up test environment variables and run tests
          export WP_TESTS_DIR=/tmp/wordpress-tests-lib
          export WP_CORE_DIR=/tmp/wordpress
          export WP_TESTS_PHPUNIT_POLYFILLS_PATH=$PWD/vendor/yoast/phpunit-polyfills
          ./vendor/bin/phpunit --testdox --verbose
