name: Kickbox Integration Plugin Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-kickbox-integration:
    name: Test KickBox integration Plugin
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: wordpress_test
          MYSQL_USER: wordpress
          MYSQL_PASSWORD: wordpress
        ports:
          - 3306:3306
        options:
          --health-cmd="mysqladmin ping --ssl-mode=DISABLED"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    container:
      image: wordpress:6.8.2-php8.1-apache
      env:
        WORDPRESS_DB_HOST: db:3306
        WORDPRESS_DB_USER: wordpress
        WORDPRESS_DB_PASSWORD: wordpress
        WORDPRESS_DB_NAME: wordpress_test
        WORDPRESS_DEBUG: 1
        WORDPRESS_CONFIG_EXTRA: "define('WP_DEBUG_LOG', true);"
      ports:
        - 80:80

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Composer
        run: |
          # Download and install Composer
          curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          composer --version

      - name: Install SVN and MySQL client
        run: |
          # Install SVN and MySQL client utilities needed by WordPress test suite
          apt-get update && apt-get install -y subversion default-mysql-client

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Copy plugin to WordPress plugins directory
        run: |
          # Create plugin directory
          mkdir -p /var/www/html/wp-content/plugins/kickbox-integration
          
          # Copy plugin files
          cp -r . /var/www/html/wp-content/plugins/kickbox-integration/
          
          # Set proper permissions
          chown -R www-data:www-data /var/www/html/wp-content/plugins/kickbox-integration
          chmod -R 755 /var/www/html/wp-content/plugins/kickbox-integration

      - name: Install WordPress test suite
        run: |
          # Install WordPress test suite
          /var/www/html/wp-content/plugins/kickbox-integration/bin/install-wp-tests.sh wordpress_test wordpress wordpress db latest true

      - name: Run PHPUnit tests
        run: |
          # Set up test environment variables and run tests
          export WP_TESTS_DIR=/tmp/wordpress-tests-lib &&
          export WP_CORE_DIR=/tmp/wordpress/ &&
          export WP_TESTS_PHPUNIT_POLYFILLS_PATH=/var/www/html/wp-content/plugins/kickbox-integration/vendor/yoast/phpunit-polyfills &&
          cd /var/www/html/wp-content/plugins/kickbox-integration &&
          ./vendor/bin/phpunit --testdox
