name: NPM Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Run ESLint
        run: npx eslint src/js --ext .js,.jsx --format=json --output-file=eslint-report.json || true

      - name: Run Prettier check
        run: npx prettier --check src/js/

