name: Kickbox Integration Plugin Tests

on:
  push:
  pull_request:

jobs:
  test-kickbox-integration:
    name: Test KickBox integration Plugin
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: wordpress_test
          MYSQL_USER: wordpress
          MYSQL_PASSWORD: wordpress
        ports:
          - 3306:3306
        options:
          --health-cmd="mysqladmin ping --ssl-mode=DISABLED"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    container:
      image: php:8.1-cli

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
